#FSR Autogenerated Content. DO NOT DELETE
"""
Copyright start
MIT License
Copyright (c) 2024 Fortinet Inc
Copyright end
"""
from .get_alerts import get_alerts
from .get_alert_by_id import get_alert_by_id
from .get_investigations import get_investigations
 
supported_operations = {'get_alerts': get_alerts, 'get_alert_by_id': get_alert_by_id, 'get_investigations': get_investigations, }